[package]
name = "espflash"
version = "1.5.2-dev"
authors = [
    "Robin Appelman <robin@icewind.nl>",
    "Jesse Braham <jesse@beta7.io>",
]
edition = "2021"
rust-version = "1.59"
description = "A command-line tool for flashing Espressif devices over serial"
repository = "https://github.com/esp-rs/espflash"
license = "GPL-2.0"
keywords = [
    "cli",
    "embedded",
    "esp",
    "xtensa",
]
categories = [
    "command-line-utilities",
    "development-tools",
    "embedded",
]
exclude = ["tests/data"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[[bin]]
name = "espflash"
path = "src/main.rs"

[dependencies]
binread = "2.2"
bytemuck = { version = "1.9", features = ["derive"] }
clap = { version = "3.1", features = ["derive"] }
comfy-table = "5.0"
crossterm = "0.23"
csv = "1.1"
dialoguer = "0.10"
directories-next = "2.0"
espmonitor = "0.7"
flate2 = "1.0"
indicatif = "0.16"
md5 = "0.7"
miette = { version = "4.7", features = ["fancy"] }
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde-hex = "0.1"
serde_plain = "1.0"
serialport = "4.1"
sha2 = "0.10"
slip-codec = "0.3"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
toml = "0.5"
xmas-elf = "0.8"
